### ISSUE TITLE
T16 - Criar o RoadMap dos Papéis

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#19]
### Descrição:
Mapear por meio do RoadMap, as funções e entregas de cada papel para as duas releases (R1 e R2).

### Tarefas
- [x] Mapear entregas do Tech Lider para a R1 e R2;
- [x] Mapear entregas do Product Manager para a R1 e R2;
- [x] Mapear entregas do DevOps para a R1 e R2;
- [x] Mapear entregas do Arquiteto para a R1 e R2.

**Estimativa de Duração** : 1 pontos 

### Comentários
Nenhum.

**Comment by gabrielademoraes** [comment]
Documento disponível em https://fga-eps-mds.github.io/2019.1-Ludum/#/roadmap-dos-papeis
