### ISSUE TITLE
T26 - Criar RoadMap do Produto

### ISSUE THREAD

**Issue by gabrielademoraes** [fga-eps-mds/2019.1-Ludum#34]
### Descrição:
Fazer o RoadMap do Produto que aborda as releases significativas, todas as sprints e o que será feito em cada uma no decorrer do projeto.

### Tarefas

- [x] Contabilizar todas as sprints;
- [x] Dividir em releases;
- [x] Definir o que será feito em cada sprint.

**Estimativa de Duração** : 5 pontos

### Comentários
Alguma informação necessária para melhor compreensão.

**Comment by LucasLermen** [comment]
Documento disponível em https://docs.google.com/document/d/13t190Hty3sfgrwEZeTkpJbWI1KAES1Hn9b5lJK3N_t0/edit?usp=sharing
